-- Migration: Fix selling prices that were stored 100x too small
--
-- Background:
--   The sync-sales and sync-offers job processors were storing Takealot's
--   `selling_price` field directly into our `*_cents` columns, but Takealot
--   actually returns the value in Rands (e.g. 329.99), not cents (32999).
--   This caused every API-sourced order and offer to display at 1/100 of
--   the real price, with knock-on errors in profit calculations and fees.
--
--   The webhook handler always treated selling_price as Rands and converted
--   correctly, so webhook-sourced orders are unaffected.
--
-- Fix:
--   Multiply selling_price_cents and unit_price_cents by 100 for orders
--   whose source = 'api'. Multiply selling_price_cents and rrp_cents by 100
--   for ALL offers (offers only come from API sync, never from webhooks
--   for these fields).
--
--   Also wipe the dependent profit_calculations and calculated_fees rows
--   so the next sync trigger recalculates them from the corrected prices.
--   The processCalculateProfits worker handles missing rows by upserting
--   so this is safe.

-- ── Fix orders ─────────────────────────────────────────────────────────────
UPDATE orders
SET
  selling_price_cents = selling_price_cents * 100,
  unit_price_cents = unit_price_cents * 100
WHERE source = 'api';

-- ── Fix offers ─────────────────────────────────────────────────────────────
-- Offer fields come exclusively from sync-offers, which had the same bug.
UPDATE offers
SET
  selling_price_cents = selling_price_cents * 100,
  rrp_cents = CASE WHEN rrp_cents IS NOT NULL THEN rrp_cents * 100 ELSE NULL END,
  -- COGS estimate was derived from the (wrong) selling price; only update
  -- estimates so we don't trample seller-provided manual COGS values.
  cogs_cents = CASE
    WHEN cogs_source = 'estimate' AND cogs_cents IS NOT NULL THEN cogs_cents * 100
    ELSE cogs_cents
  END;

-- ── Wipe stale derived data so it gets recalculated cleanly ────────────────
-- These will be regenerated by the next initialSync / calculate-profits run.
DELETE FROM calculated_fees;
DELETE FROM profit_calculations;

-- ── Wipe stale alerts that were generated from wrong profit numbers ────────
-- Bulk loss-maker / margin-drop alerts created during the bad-data window
-- will be regenerated correctly on the next profit calc.
DELETE FROM alerts
WHERE alert_type IN ('loss_maker', 'margin_drop');
